<a href="https://colab.research.google.com/github/Patelt13/ML_Assignment1/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Patel Tirth Nareshbhai
UTA ID: **1001869576** 



Programming Assignment 1: matrix factorization using gradient descent 

In [3]:
import numpy as np
import pandas as pd
import progressbar as pb
import numpy

In [19]:
def Matrix_Factorization(T1, P1, P2, T2, steps=1000, alpha=0.0002, beta=0.02):
    P2 = P2.T #Transpose of matrix P2
    for step in pb.progressbar(range(steps)): # to keep track of loops
        for i in range(len(T1)):
            for j in range(len(T1[i])):
                if T1[i][j] > 0:
                    eij = T1[i][j] - numpy.dot(P1[i,:],P2[:,j])
                    for k in range(T2):
                        P1[i][k] = P1[i][k] + alpha * (2 * eij * P2[k][j] - beta * P1[i][k])
                        P2[k][j] = P2[k][j] + alpha * (2 * eij * P1[i][k] - beta * P2[k][j])
        eR = numpy.dot(P1,P2)
        e = 0
        for i in range(len(T1)):
            for j in range(len(T1[i])):
                if T1[i][j] > 0:
                    e = e + pow(T1[i][j] - numpy.dot(P1[i,:],P2[:,j]), 2)
                    for k in range(T2):
                        e = e + (beta/2) * (pow(P1[i][k],2) + pow(P2[k][j],2))
        if e < 0.001:
            break
    return P1, P2.T

**Add input file to check matrix factorization function.**

In [20]:
input1 = open("input1.csv")
input1 = np.loadtxt(input1, delimiter=",")
print(input1)

[[6. 0. 3. 7. 2. 5. 4. 2. 4. 3. 0. 5. 0. 6. 0. 9. 2. 5. 4. 6. 1. 6. 4. 0.
  0. 3. 4. 1. 9. 1. 8. 0. 9. 1. 6. 4. 8. 6. 0. 0. 3. 9. 1.]
 [2. 0. 0. 8. 7. 3. 1. 2. 2. 0. 9. 6. 2. 7. 6. 6. 4. 7. 7. 7. 1. 6. 7. 5.
  4. 0. 5. 3. 3. 1. 7. 1. 1. 8. 7. 3. 5. 2. 4. 6. 6. 8. 1.]
 [0. 4. 0. 6. 8. 5. 4. 6. 0. 7. 4. 7. 1. 4. 3. 6. 2. 1. 1. 9. 7. 7. 6. 4.
  5. 7. 1. 9. 6. 2. 8. 3. 0. 3. 0. 2. 5. 9. 3. 1. 8. 8. 4.]
 [8. 8. 2. 5. 6. 9. 2. 3. 9. 9. 5. 3. 7. 3. 1. 8. 5. 6. 9. 2. 7. 9. 0. 4.
  1. 3. 3. 3. 2. 7. 2. 1. 6. 2. 9. 3. 5. 4. 6. 2. 7. 3. 4.]
 [8. 8. 9. 6. 6. 1. 2. 9. 8. 3. 8. 9. 7. 7. 1. 4. 3. 1. 1. 2. 5. 7. 5. 5.
  4. 4. 8. 5. 9. 7. 5. 1. 5. 4. 3. 0. 1. 4. 9. 5. 3. 9. 6.]
 [3. 5. 7. 8. 4. 5. 1. 0. 9. 6. 3. 6. 6. 7. 4. 5. 5. 5. 2. 3. 4. 0. 0. 8.
  4. 2. 1. 8. 1. 8. 7. 1. 2. 3. 5. 0. 5. 7. 2. 4. 7. 9. 2.]
 [4. 1. 7. 7. 2. 3. 1. 8. 4. 1. 6. 1. 8. 5. 4. 9. 3. 9. 9. 4. 7. 4. 0. 9.
  0. 0. 9. 4. 4. 8. 1. 2. 7. 0. 4. 3. 0. 3. 2. 6. 6. 2. 0.]
 [5. 9. 3. 5. 7. 0. 5. 4. 1. 7. 5. 6. 5. 8. 6. 9. 6. 0. 2. 2. 

In [21]:
input2 = open("input2.csv")
input2 = np.loadtxt(input2, delimiter=",")
print(input2)

[[8. 0. 0. ... 2. 0. 0.]
 [6. 2. 0. ... 0. 2. 8.]
 [5. 4. 2. ... 1. 2. 9.]
 ...
 [4. 5. 4. ... 1. 1. 4.]
 [7. 4. 4. ... 3. 1. 5.]
 [0. 7. 4. ... 4. 7. 5.]]


In [22]:
T1 = np.array(input1)
N = len(T1)
M = len(T1[0])
T2 = 2

P1 = np.random.rand(N,T2)
P2 = np.random.rand(M,T2)

nP1, nP2 = Matrix_Factorization(T1, P1, P2, T2)
nT1 = numpy.dot(nP1, nP2.T)

100% (1000 of 1000) |####################| Elapsed Time: 0:00:18 Time:  0:00:18


**Output for Input File 1**

In [23]:
nT1

array([[ 5.00049957,  4.5639462 ,  4.46063952,  5.17939135,  4.84145917,
         4.60028416,  3.94615589,  4.79468661,  4.63147003,  3.57683474,
         5.33516925,  5.72660141,  5.57589758,  4.89746955,  4.07629078,
         5.56042012,  3.266832  ,  4.14564641,  4.70373041,  4.25218393,
         4.57654103,  4.50621951,  4.88728176,  4.2117077 ,  3.36209714,
         5.20098539,  5.2928733 ,  5.13280886,  4.88305099,  3.3490866 ,
         5.23077552,  2.42230995,  4.79306383,  4.19654491,  4.63510836,
         4.28816157,  4.14688693,  5.66562066,  3.55972249,  4.34650644,
         5.20194506,  5.65230268,  3.93790746],
       [ 5.04024277,  4.58940311,  4.87950488,  4.83339858,  5.07423589,
         4.52909998,  4.16860189,  3.99540599,  4.18691544,  3.37447126,
         5.87665088,  5.9275518 ,  5.9456979 ,  4.79204591,  4.51903743,
         4.86425867,  3.00689575,  4.08083344,  4.9571586 ,  4.36633618,
         4.59197328,  3.25433777,  5.73477991,  3.53436911,  3.13767891,
   

In [25]:
T1 = np.array(input2)
N = len(T1)
M = len(T1[0])
T2 = 2

P1 = np.random.rand(N,T2)
P2 = np.random.rand(M,T2)

nP1, nP2 = Matrix_Factorization(T1, P1, P2, T2)
nT1 = numpy.dot(nP1, nP2.T)

100% (1000 of 1000) |####################| Elapsed Time: 0:03:19 Time:  0:03:19


**Output for Input file 2**

In [ ]:
nT1

array([[4.66980923, 5.22066624, 5.11011736, ..., 4.64809746, 5.38159376,
        4.96056768],
       [5.82756976, 4.2195485 , 3.67802049, ..., 5.03708097, 3.5063467 ,
        5.41529319],
       [4.24613391, 5.47919851, 5.50740745, ..., 4.46989362, 5.91707508,
        4.75775512],
       ...,
       [5.50019258, 4.31441593, 3.86166388, ..., 4.86449423, 3.77344359,
        5.22315519],
       [5.99096405, 3.94424182, 3.31832747, ..., 5.04740745, 3.0543092 ,
        5.43421314],
       [6.78754054, 5.20155008, 4.62126086, ..., 5.96225534, 4.48511163,
        6.40423598]])